plugins {
    id 'fabric-loom' version '1.2.3'
    id 'maven-publish'
}

group = 'com.example'
version = '1.0.0'

repositories {
    mavenCentral()
    maven { url = 'https://maven.fabricmc.net/' }
}

dependencies {
    minecraft 'com.mojang:minecraft:1.21.5'
    mappings 'net.fabricmc:yarn:1.21.5+build.1:v2'
    modImplementation 'net.fabricmc.fabric-api:fabric-api:0.123.2+1.21.5'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release.set(17)
}

loom {
    splitEnvironmentSourceSets()
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
}
